### ISSUE TITLE
Allow upload of files on my local machine instead of requiring they be hosted somewhere

### ISSUE THREAD

**Issue by alecfwilson** [lambtron/emojipacks#1]

**Comment by lambtron** [comment]
Thanks for the issue. It is possible to upload locally hosted images, just takes a few extra steps.

Check out this fork and commit from @wcjohnson11: https://github.com/wcjohnson11/emojipacks/commit/cea65d9f5db49f361d6f68241fa0f2bf0b086d39

Host the images locally, then in the .yaml file, provide the relative path to the image.

Can you try that and see if that works?

**Comment by alecfwilson** [comment]
```
 $ emojipacks                                                                                                                                                           [13:42:13]
Slack subdomain: redacted
Email address login: *@**.com
Password: redacted
Path or URL of Emoji yaml file: ./emoji.yaml
```

It just hangs here. I forked @wcjohnson11's fork, and replaced his images with mine. At first, I thought it was an issue with file types, so I ensured they are all pngs. Also, 2 factor auth is not enabled for my Slack account, so that isn't the issue. It's simply not logging in.

**Comment by lambtron** [comment]
That is very strange and I'm not sure what the problem might be.

Can you try running `emojipacks` with the debug flag enabled?

```
$ emojipacks -d
```

Then, after it hangs there, exit the process. The debug flag will write the HTML to `./test` folder (there should be a `./test/Slack.html`). Can you open that in the browser and see what that page looks like?

Chances are something is preventing the script from logging in, just not sure exactly what. Hopefully the page Slack.html will have the error message to tell us what went wrong.

Let me know if you have any questions about this!

**Comment by austinemayer** [comment]
i am currently getting the same issue. when running the debug flag. it says 
Uh oh! Error: ENOENT, no such file or directory '/Users/austinemayer/Sites/emojipacks/test/Slack.html'

EDIT: found a work around.
upload your image dir to github.
view raw image on github.
copy url path and replace local path for github path in the yaml file.

**Comment by alecfwilson** [comment]
@austinemayer - thanks for the tip, it still hangs for me. I've let it hang for up to 10 minutes before killing it, how long does it take?

@lambtron - when I run emojipacks with the debug flag and ls -a, there is no test directory, and there is no Slack.html file anywhere. Are you sure the debug flag works?

**Comment by austinemayer** [comment]
@alecfwilson Should be right away. Just make sure you have everything set up correctly and your images follow the restrictions slack placed on emoji uploads. Your yaml file is properly set up, similar to the example yaml files given and then placed in the packs dir. I just uploaded 1600 emojis so I know it works properly.

**Comment by alecfwilson** [comment]
Hmmm... I am almost positive there are no issues with the format of the images, but I'll double check and test with some emojis from the verified packs as the urls. 

Does the yaml file _have_ to be in packs/? I didn't place mine in a packs directory, I guess I might as well try that...

**Comment by alecfwilson** [comment]
Ok, so I moved my yaml files into packs/. I also split them into smaller bunches so I could test multiple different uploads. I also placed the hipchat.yaml file from @lambtron's repo to test that uploads were working correctly.

The hipchat pack uploaded correctly using the yaml URL from my repo. However, all of my packs still refuse to upload. All my images are within Slack restrictions, and the raw Github image URLs are functioning correctly. Is there an issue with hosting images from Github? That's the only difference I can see between my yaml files and the Hipchat one copied from @lambtron's repo.

**Comment by austinemayer** [comment]
@alecfwilson I believe the problem lies within your spacing. 
YAML uses a fixed indentation scheme to represent relationships between data layers. Salt requires that the indentation for each level consists of exactly two spaces. Do not use tabs.

**Comment by alecfwilson** [comment]
@austinemayer nice catch, I had forgotten that about YAML, but I just checked, and my local files _are_ using spaces rather than tabs. For some reason, Github is converting them to tabs. Even when I edit the files on Github, two consecutive spaces are turned into tabs. Any idea why this would happen?

**Comment by alecfwilson** [comment]
@austinemayer I figured out the issue, I had to change my editorconfig, then replace the spaces with spaces again to get it to write to Github correctly. Thanks for pointing out the problem!

**Comment by lambtron** [comment]
Closing this one, but feel free to reopen if necessary :)
