### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by dsthedev** [lambtron/emojipacks#102]
Fresh install, tried reinstalling, tried googling the error, still getting this error:

`Slack subdomain: d******v`
`Email address login: d******v@gmail.com`
`(node:4044) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: process.stdin.setRawMode is not a function`

**Comment by zachfeldman** [comment]
Hi @dsthedev thanks for letting us know. What version is this?

Also see this issue:
https://github.com/lambtron/emojipacks/issues/100

May want to wait a few hours or a day or two and then try again, you might just be getting rate limited.

**Comment by dsthedev** [comment]
Most recent version of Windows 10, gitbash, node/npm and this tool.  I tried it on my macbook minutes afterward and it worked, so I'm not too worried about it now.  I did check #100 before posting this, but it wouldn't even let me get past entering my email.

Any idea how/why I'd be getting rate limited?  It was my 2-5th attempt.

Either way, I can't check it on that machine until Monday.  But I'll check it then and report back if it worked or not.

**Comment by zachfeldman** [comment]
Sounds good!

**Comment by hvisage** [comment]
Good day,
I'm also getting this, after succesfully loading some of the emojipacks, I'm trying to load the SlackMojis.com pack:


```
-y http://slackmojis.com/emojis.yaml
Starting import
Got tokens
Logged in
Getting emoji page
(node:7479) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot convert undefined or null to object
debian@linked-clone-of-debian8netinst:~$
```

**Comment by zachfeldman** [comment]
Hey @hvisage what operating system are you running in? Debian? If so unfortunately I don't have a Debian setup to try to replicate your issue on. Could you try throwing some debug statements in there and seeing if anything is being returned correctly?

**Comment by dsthedev** [comment]
Late reply, but I tried it again on my Windows machine and same thing happened...  I'm just going to use it on my Mac for now.  If there is any way I can help with debugging, logs, etc just let me know and I'll see what I can do.  Output again fwiw:

`Slack subdomain: d******v`
`Email address login: d******v@gmail.com`
`(node:13552) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: process.stdin.setRawMode is not a function`

This can't be something like what others have encountered, as it's failing at **email entry**, I don't even get a chance to enter my password to even attempt connecting.

**Comment by dsarauer** [comment]
Just a note, it looks like if you are using GitBash on Windows 10 this error pops up on email entry.  If you launch the Node.js command line in Windows this works as expected.

**Comment by zachfeldman** [comment]
@dsarauer interesting. That's at least one solution (if people are running windows 10)

@dsthedev can you try the suggestions in this thread and see if they help (see the last 2 comments):
https://github.com/workshopper/stream-adventure/issues/171

**Comment by zachfeldman** [comment]
@dsthedev are you still having this issue?

**Comment by hvisage** [comment]
@zachfeldman I've since retried it (from a place with bit better bandwidth) and it worked fine.

**Comment by zachfeldman** [comment]
Awesome!
