### ISSUE TITLE
UnhandledPromiseRejectionWarning error

### ISSUE THREAD

**Issue by djk** [lambtron/emojipacks#114]
Hi there,

I'm getting the below issue when trying to use https://slackmojis.com/emojis.yaml.

I turned off 2FA in case it was causing issues and the same problem happened. The number (in the below case "5778") next to 'node' appears to change each time I run it. I don't know if this is relevant or not.

I have tried on two different Macs and also a Fedora VM, all using node v7.10.0. I used the npm install method and also on one of the Macs built from the checked out repo. Same issue across the board.

Any ideas on how to get past this?

> Password: ***********************
Starting import
Got tokens
2FA Code: ******
Logged in
Getting emoji page
(node:5778) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot convert undefined or null to object
(node:5778) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by zachfeldman** [comment]
Hi @djk , haven't seen this error yet. Can you maybe try to figure out what line this is happening on?

**Comment by djk** [comment]
I'll have another go @zachfeldman and see if I can!

**Comment by djk** [comment]
@zachfeldman I tried again this time with Node 8 and get the same problem. I used the "-d" flag but it's not outputting anything else apart from this error.

Is there anything else I can try?

**Comment by zachfeldman** [comment]
@djk that's weird, and you're not seeing a stack trace? 

Maybe try running the code that makes up the emojipacks bin from the node console to see if you get a more specific line number:
https://github.com/lambtron/emojipacks/blob/master/bin/emojipacks

Paging @lambtron  or @hugovk ?

**Comment by djk** [comment]
Hey @zachfeldman. I'm having trouble running this in the console to be honest, I'm not sure I'm doing it right. Can you point me in the right direction?

**Comment by zachfeldman** [comment]
Did you try running the `node` command in the same directory that the bin usually runs in, then pasting in the commands from that bin? Can you be more specific about what you've tried?

**Comment by djk** [comment]
> djk@djks-iMac  ~/node_modules/emojipacks/bin  node
>
> var program = require('commander');
undefined
> var Prompt = require('../lib/prompt');
undefined
> var Slack = require('../lib/slack');
undefined
> var Pack = require('../lib/pack');
undefined
> var co = require('co');
undefined
>
> /**
...  * Usage.
...  */
undefined
>
> program
Command {
  commands: [],
  options: [],
  _execs: {},
  _allowUnknownOption: false,
  _args: [],
  _name: '',
  Command: [Function: Command],
  Option: [Function: Option] }
>   .version(require('../package').version)
Invalid REPL keyword
>   .option('-d, --debug', 'Run in debug mode')
Invalid REPL keyword
>   .option('-s, --subdomain [value]', 'Your Slack subdomain')
Invalid REPL keyword
>   .option('-e, --email [value]', 'Admin email address')
Invalid REPL keyword
>   .option('-p, --password [value]', 'Password for admin email')
Invalid REPL keyword
>   .option('-y, --pack [value]', 'YAML emoji pack')
Invalid REPL keyword
>   .parse(process.argv);
Invalid REPL keyword
>
> /**
...  * Start process.
...  */
undefined
>
> co(function *() {
...   var user = yield Prompt.start(program.subdomain, program.email, program.password, program.pack);
...   var pack = yield Pack.get(user.pack);
...   user.emojis = pack.emojis;
...   var slack = new Slack(user, program.debug);
...   yield slack.import();
...   process.exit();
... });
Slack subdomain: Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }
> aEmail address login: mAre you sure that is an email address? :)
Email address login:
> Are you sure that is an email address? :)
Email address login:
(To exit, press ^C again or type .exit)
> Are you sure that is an email address? :)
>Email address login:

So after the "Slack subdomain: Promise" part, I try to type in the subdomain and it's taking each individual letter and telling me it's not a valid email address. It's like I'm hitting return after each character of the Slack subdomain I'm trying to enter.

Am I doing this wrong? Sorry, I'm no node dev.

**Comment by zachfeldman** [comment]
That's ok @djk ! Not sure I'd call myself a primary node dev either but I'll try to help.

There are several errors as you paste the code in the middle. I would try to address those - you may have to modify the source code just a bit from how the bin would normally run in order to get it to work. My hope is that as you do this, you'd figure out the source of your error. Classic debugging!

@lambtron wrote all of the original code, so I'm hoping he can chime in here with some ideas...I'm just maintaining at this point and try to keep the tracker clear! I'll Tweet at him to try to get some more eyes...

**Comment by djk** [comment]
So I cut out the comments and the usage details...

It's losing some formatting so I put it in a [gist](https://gist.github.com/djk/d2630c7f8e7814567b1a88309c779835)

Seems to do the same thing where it won't actually let me enter the Slack subdomain...

Appreciate you taking the time to help by the way! Thanks!

**Comment by lambtron** [comment]
Thank you everyone for your comments. I'll take a look this evening to see what the issue might  be. Sorry I have been unresponsive!!

**Comment by lambtron** [comment]
I tried the same inputs as @djk and got the same error. I suspect it has to do with the CLI being unable to parse the format that is presented in your target yaml file.

I'm going to see if I can rewrite the parser so that it can accept it. Thanks for your patience!

**Comment by lambtron** [comment]
Ok, the new version `0.2.1` should fix this. Try that and let me know if that works!!

**Comment by djk** [comment]
All working now! Thanks @lambtron!

**Comment by zachfeldman** [comment]
Go @lambtron go!

**Comment by Santana1053** [comment]
Hello, using version 0.2.1 and still seeing this issue
