### ISSUE TITLE
Handle 2FA cycle

### ISSUE THREAD

**Issue by rgbkrk** [lambtron/emojipacks#12]
Emojipacks doesn't work on accounts that are 2FA enabled

```
emojipacks
Slack subdomain: redacted
Email address login: [REDACTED]
Password: **************
Path or URL of Emoji yaml file: http://www.emojipacks.com/packs/businessfish.yaml
Starting import
Got tokens
Logged in
Upload crumb is undefined
Uh oh! Error: Login error: could not get emoji upload crumb for https://redacted.slack.com
```

Disabling 2FA works, but I'm sure there's a way to handle the full circle.

```
$ emojipacks
Slack subdomain: redacted
Email address login: [REDACTED]
Password: **************
Path or URL of Emoji yaml file: http://www.emojipacks.com/packs/businessfish.yaml
Starting import
Got tokens
Logged in
Upload crumb is s-1442851577-a17fca3392-☃
Getting emoji page
Uploading bfexcite with http://i.imgur.com/cUqre6P.png
Uploading bfkiss with http://i.imgur.com/NryT58n.png
Uploading bfquestion with http://i.imgur.com/8RwFbed.png
Uploading bfdetermine with http://i.imgur.com/rlJ2w4w.png
```

**Comment by lambtron** [comment]
In order to get around the TFA issue, the tool would have to use Slack's oauth. I can take a look into this to see how it can be done. Thanks!

**Comment by joseche** [comment]
I don't have 2FA enabled and I am getting that same error:

Uh oh! Error: Login error: could not get emoji upload crumb for .....

**Comment by joseche** [comment]
(~/git/emojipacks)$ emojipacks
Slack subdomain: .......
Email address login: .......@gmail.com
Password: ********
Path or URL of Emoji yaml file: ./packs/starwars.yaml
Starting import
Got tokens
Logged in
Upload crumb is undefined
Uh oh! Error: Login error: could not get emoji upload crumb for https://.......slack.com

**Comment by pierrenel** [comment]
same as @joseche

**Comment by elldritch** [comment]
@lambtron are you sure this can be done using OAuth? I was under the impression that only gave access to the Slack API, which doesn't have an emoji upload endpoint.

**Comment by safusu** [comment]
Throwing my two cents here, but I was able to get it to work by using the web URL and not a path to the yaml file.

**Comment by musus** [comment]
I was able to do it when I turned off a Two-Factor Authentication.

**Comment by zachfeldman** [comment]
See this PR https://github.com/lambtron/emojipacks/pull/78
