### ISSUE TITLE
--harmony doesn't work in Ubuntu

### ISSUE THREAD

**Issue by jasonmebw** [lambtron/emojipacks#13]
Seems that flag doesn't play well with some distros, but works on Mac.   See here: https://github.com/hiddentao/melkor/issues/12

I removed "--harmony" and worked for me in Ubuntu 14.04.3.

**Comment by yuvilio** [comment]
Confirming this bug on my ubuntu with node (using nvm , node version `v4.2.2`)

**Comment by elldritch** [comment]
Can confirm, this occurs for me in 14.04.3 LTS with node 5.6.0

**Comment by thorsummoner** [comment]
to fix, get the latest node from https://nodejs.org/en/

```
sudo su
cd /opt
wget https://nodejs.org/dist/v4.3.1/node-v4.3.1-linux-x64.tar.xz
tar -xvf node-v4.3.1-linux-x64.tar.xz
cd /usr/bin
mv node node-lts
mv nodejs nodejs-lts
mv node-gyp node-gyp-lts
ln -s /opt/node-v4.3.1-linux-x64/bin/node nodejs
ln -s nodejs node
```

As well I changed the line in `/usr/local/bin/emojipacks`
to

```
#!/usr/bin/node --harmony
```
