### ISSUE TITLE
test directory can't be created

### ISSUE THREAD

**Issue by jfexyz** [lambtron/emojipacks#15]
`emojipacks -d` kept failing until I manually ran `mkdir /usr/local/lib/node_modules/emojipacks/test`.

I was getting this error:

```
Uh oh! Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/emojipacks/test/Slack.html'
```

**Comment by jfexyz** [comment]
To be clear, the `test` directory was not at that location after installing with `npm -g`

**Comment by lambtron** [comment]
oh thank you, will fix this.

**Comment by zachfeldman** [comment]
@joshuajabbour closing because it has been a long time. If this is still a problem please comment!
