### ISSUE TITLE
New layout breaks upload completely

### ISSUE THREAD

**Issue by ohcibi** [lambtron/emojipacks#157]
It appears that slack has changed its layout in the admin area and now the upload fails because the `upload crumb` cannot be found. I'm just trying to fix that but I cannot see what the 'Upload crumb' should be, nor can I remember what It could have been in the old layout. If someone could just tell me the meaning of the old fields and maybe even a mapping to the new fields, I'd be happy to contribute the necessary code changes asap.

I'm mainly speaking about this part of `lib/slack.js` but I might be missing other parts which I'd need to be pointed out if any 8-)

```javascript
      var opts = this.opts;
      var r = req({
        url: opts.url + emojiUploadImagePath,
        method: 'POST',
        jar: opts.jar,
        followAllRedirects: true
      }, function(err, res, body) {
        if (err || !body) return reject(err);
        resolve(body);
      });
      var form = r.form();

      //// those fields, most important 'crumb' which if not found throws the error that stops everything a few lines above
      form.append('add', '1');
      form.append('crumb', opts.uploadCrumb);
      form.append('name', name);
      form.append('mode', 'data');
      form.append('img', req(emoji));
```

**Comment by jackellenberger** [comment]
Hi! this is fixed with https://github.com/lambtron/emojipacks/pull/155

There aren't any contribution guidelines so I don't know if we should @ someone to get a review. If no one is around in another few days I'll start shoutin'.

**Comment by ohcibi** [comment]
I just tested it by uploading ~500 emojis to our new slack space..... :ohcibi:

**Comment by JustOneMoreDog** [comment]
this never got pushed to master it would seem.  Also emojipack no longer seems to work after your changes.  I am probably doing something wrong though.  I installed node and npm and then did a git clone.  I went into the directory and changed the two files you changed.  Then I ran make.  Now whenever I run the command emojipacks, it does not output anything at all and just returns.  Do you have any insight on if I am doing this wrong?

**Comment by jackellenberger** [comment]
Hi @picnicsecurity! It' hasn't been reviewed so I don't want to get it into master just yet. `make` shouldn't have anything to do with it, I think that's just for CI testing. I would double check that the diff on `lib/slack.js` is identical, or just checkout the branch itself. As for no output - are you giving emojipacks an input? It should ask for a slack org, username, password, and a source yaml of emoji to upload. Are you getting to the step where those are asked for?

**Comment by ohcibi** [comment]
@picnicsecurity

* this issue here is not about the PR at #155 which has it's own comments section for exactly those problems that happen with the changes introduced by the PR (although both the issue and the PR had the same motivation for being created)
* I'd never expect the way you tested this to work as PRs have rarely branched of the exact commit you are cloning when you found the PR on github. So you want to (as always with git) make sure that you have the exact commit the PR is about and definitely **dont't** want to **apply the changes yourself**. To checkout the exact commit, just do

```sh
git clone <therepositoryurl>
git remote add <github-user-name-of-user-that-made-pr> <repositoryurl-of-fork-with-pr>
git fetch <github-user-name-of-user-that-made-pr>
git checkout <branch-name-of-pr>

### Now you are on the very changeset that the PR is about
### and are actually able to test if it works or not
```

**Comment by JustOneMoreDog** [comment]
@ohcibi 

I am still learning git so forgive my silly questions here.  What would be the url of the repository with the pr?

```
root@:~# git clone https://github.com/lambtron/emojipacks.git
Cloning into 'emojipacks'...
remote: Counting objects: 1106, done.
remote: Total 1106 (delta 0), reused 0 (delta 0), pack-reused 1105
Receiving objects: 100% (1106/1106), 4.47 MiB | 0 bytes/s, done.
Resolving deltas: 100% (480/480), done.
Checking connectivity... done.
root@:~# cd emojipacks/
root@:~/emojipacks# git remote add jackellenberger https://github.com/lambtron/emojipacks/pull/155
root@:~/emojipacks# git fetch jackellenberger
fatal: repository 'https://github.com/lambtron/emojipacks/pull/155/' not found
root@:~/emojipacks# git remote remove jackellenberger
root@:~/emojipacks# git remote add jackellenberger https://github.com/lambtron/emojipacks/pull/155/commits/3651dd8aaafbcd3fe22c25742e55e73cd63a8dcd
root@:~/emojipacks# git fetch jackellenberger
fatal: repository 'https://github.com/lambtron/emojipacks/pull/155/commits/3651dd8aaafbcd3fe22c25742e55e73cd63a8dcd/' not found
root@:~/emojipacks#
```

**Comment by jackellenberger** [comment]
@picnicsecurity you can see the branch on the pr page, `update-selector-for-upload-page-rewrite`
![image](https://user-images.githubusercontent.com/6370918/44675837-2e15d880-a9f7-11e8-81c7-0c7cbdf9c6f1.png)


So your commands should be 
```
git clone git@github.com:lambtron/emojipacks.git
cd emojipacks/
git remote add jackellenberger git@github.com:jackellenberger/emojipacks.git
git fetch jackellenberger update-selector-for-upload-page-rewrite
git checkout --track jackellenberger/update-selector-for-upload-page-rewrite
```

**Comment by JustOneMoreDog** [comment]
Thank you so much for your help :D
