### ISSUE TITLE
hipchat > firstworldproblems access denied causing failure

### ISSUE THREAD

**Issue by jfexyz** [lambtron/emojipacks#16]
The [`firstworldproblems` emoji](https://dujrsrsgsd3nh.cloudfront.net/img/emoticons/firstworldproblems-1414025630@2x.png) is returning access denied. This causes hipchat imports to freeze.

**Comment by lambtron** [comment]
ah ok. i have to upload all of these to imgur, then remap it, then i think it'll work.

**Comment by ascendantlogic** [comment]
My uploads still freeze on this particular emoji.

**Comment by shaneedwards** [comment]
Same issue occurring today and it appears to happen on 'freddie' after I manually removed the FWP node from the hipchat.yaml file.

**Comment by zachfeldman** [comment]
Closing this for now as this was a long-ish time ago. Please let me know if this is still a problem and we'll investigate!
