### ISSUE TITLE
twitch pack doesn't seem to work

### ISSUE THREAD

**Issue by SabinDeus** [lambtron/emojipacks#17]
It goes through the motions but nothing is actually uploaded.

**Comment by lambtron** [comment]
hmm weird. are you passing `https://raw.githubusercontent.com/lambtron/emojipacks/master/packs/twitch.yaml`?

**Comment by SabinDeus** [comment]
Yes.

**Comment by SabinDeus** [comment]
I suspect it is because the URL does not contain what appears to be an image filename, nor do the response headers from the server send back a content-disposition header with a file name in it, but I have no idea that is just an educated guess

**Comment by lambtron** [comment]
Hmmm i'll take a look, thank you

**Comment by SabinDeus** [comment]
Figured it out - apparently Slack custom emoji names have to be all lower case, whereas the Twitch emojipack has uppercase characters in most of the names and those fail

**Comment by lambtron** [comment]
Oh shoot sorry about that. I can go and fix that.

**Comment by nickgal** [comment]
I actually created a little ruby script to generate the twitch global & subscriber emotes. It's been working great for me for a few months now. 
https://github.com/nickgal/emojipacks-twitch

**Comment by hugovk** [comment]
@Sabin1936 This was fixed in https://github.com/lambtron/emojipacks/pull/28 so this issue can be closed.
