### ISSUE TITLE
"Foodz" YAML file is missing?

### ISSUE THREAD

**Issue by teleject** [lambtron/emojipacks#2]
http://www.emojipacks.com/packs/foodz.yaml gives me "Not Found" message.

**Comment by teleject** [comment]
Ah. Looks like the link off the site goes to http://www.emojipacks.com/packs/foodz.yaml, when the filename doesn't have a "z": http://www.emojipacks.com/packs/food.yaml

**Comment by lambtron** [comment]
Oh shoot. Good catch. Will fix this.

**Comment by lambtron** [comment]
Updated, now it is just `food` and it should work.
