### ISSUE TITLE
Adding Slackemojis pack.

### ISSUE THREAD

**Issue by kyletaylored** [lambtron/emojipacks#21]
Converted the slackmojis.com list into a pack, has a bunch all in one.
[slackemojis.txt](https://github.com/lambtron/emojipacks/files/80355/slackemojis.txt)

**Comment by jkupferman** [comment]
Slackmojis.com guy here. I just added an yaml endpont to slackmojis that should make bulk importing via emojipacks easier (now with 100% less regex-fu!)

http://slackmojis.com/emojis.yaml

@lambtron let me know if this format works for emojipacks

**Comment by ckcollab** [comment]
@jkupferman did not work for me, just froze at "Getting emoji page"

**Comment by kyletaylored** [comment]
@ckcollab which one? The one @jkupferman posted isn't formatted correctly, since I'm guessing it's key based.

You can even paste the link to the txt file in my comment and it'll run just fine.

<img width="704" alt="screen shot 2016-01-08 at 1 08 02 am" src="https://cloud.githubusercontent.com/assets/1759794/12192493/9af9ea9e-b5a4-11e5-9ae8-c073239e9b45.png">

**Comment by ckcollab** [comment]
@jkupferman's link -- that's why I tagged him, unless I'm confused?

And yeah, that's probably why it didn't work!

**Comment by kyletaylored** [comment]
Hah, sorry, I wasn't paying attention. It's late. ;)

**Comment by ckcollab** [comment]
S'all good mang ;)

**Comment by lambtron** [comment]
https://github.com/lambtron/emojipacks/commit/aa65fdbaa2d37b05943266f26f0b5d1f8252655f

Thanks everyone!!

**Comment by jkupferman** [comment]
Slackmojis allows for multiple emojis with the same name (e.g. mario, carlton), does emojipacks just take the first one?

**Comment by lambtron** [comment]
Emojipacks will take the first one; every subsequent one will just be ignored. :(
