### ISSUE TITLE
Add Hipchat emoji pack

### ISSUE THREAD

**Issue by kyletaylored** [lambtron/emojipacks#23]
Went ahead and wrote a little YAML file for Hipchat emojis based on this page: https://www.hipchat.com/emoticons

[hipchat.yaml](https://github.com/lambtron/emojipacks/files/96703/hipchat.yaml.txt)

**Comment by kyletaylored** [comment]
jk, that file doesn't work (indenting issues).

[hipchat.yaml.txt](https://github.com/lambtron/emojipacks/files/113217/hipchat.yaml.txt)

**Comment by TheTedAdams** [comment]
Is this different from https://github.com/lambtron/emojipacks/blob/master/packs/hipchat.yaml referenced in the readme?

**Comment by kyletaylored** [comment]
Ah, true dat, not different. JK :)
