### ISSUE TITLE
More emojis

### ISSUE THREAD

**Issue by spoike** [lambtron/emojipacks#29]
Just wanted to let you all know I made some yml files and published on github over here https://github.com/spoike/emojis

The emojis have been uploaded on imgur and the yml files are referencing them. It is possible to use the raw urls specified in the README file in the emojipacks program.

**Comment by lambtron** [comment]
Thank you, I'll make sure they're added!

**Comment by hugovk** [comment]
Added in PR https://github.com/lambtron/emojipacks/pull/57.
