### ISSUE TITLE
Request: SAML / SSO support

### ISSUE THREAD

**Issue by gnomishperson** [lambtron/emojipacks#33]
So organizations that use SAML for SSO support do not currently work, because the login form is not used in the fashion this script desires. Don't know if this is something that could even adequately be supported, but would be neat if it could.

**Comment by ngunia** [comment]
This is possible, you need to use the Chrome inspector when logged into slack in browser, to get your cookie session string.  I just copied the whole cookie string and passed it into a different script (was easier to edit) and it worked.  If someone wants to hack that in it should work, you'll just have to set it up to skip over the login code so it doesn't error out before you can pass the cookie.

**Comment by kdim953** [comment]
@ngunia Can you share how you accomplished this?

**Comment by zachfeldman** [comment]
@ngunia @kdim953 @gnomishperson closing for now but glad to accept a PR solution. We did implement 2fa recently so I'm sure this is possible too!
