### ISSUE TITLE
Upload crumb is undefined

### ISSUE THREAD

**Issue by BoldBigflank** [lambtron/emojipacks#36]
I'm able to log in, but the upload crumb is undefined and fails. Has the Slack website changed somehow breaking the system?

**Comment by BoldBigflank** [comment]
In my testing, it seems that the login isn't actually logging in, so the page it's trying to pull the crumb from is a "You must sign in first" page.

**Comment by masonjames** [comment]
Just tested this quickly today and ran into the same error message. Could be due to 2FA? 

Suggestion: Better system for authenticating than giving the user/pass combo.

**Comment by JT703** [comment]
i got this error as well, then i looked up my password and it was wrong. after entering the correct password, it worked.

**Comment by markogresak** [comment]
I've double checked if the password is correct, tried to use 2FA code and nothing worked. Got it working after I've disabled the 2FA, which is a terrible solution. The support for this was already requested in #12.

**Comment by evanberkowitz** [comment]
I similarly encountered this error, but it was my own fault:  I had typed my email incorrectly.

It reported
```
(node:71594) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Login error: could not get emoji upload crumb for https://[redacted].slack.com
(node:71594) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

and then just hung indefinitely, until I hit `ctrl+c`.

**Comment by zachfeldman** [comment]
See this PR: 

https://github.com/lambtron/emojipacks/pull/78
