### ISSUE TITLE
SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by Shpigford** [lambtron/emojipacks#4]
I've installed via both `npm` and `git clone`, but result in an error when I try to run `emojipacks`

```
> emojipacks

/Users/USERNAME/Work/Development/emojipacks/bin/emojipacks:22
co(function *() {
            ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by lambtron** [comment]
Ah good catch. What node version are you using?

Emojipacks requires at least node version 0.11.x, since it uses generators and `*` functions.

Can you try updating node version and see if that fixes it? :)

**Comment by lambtron** [comment]
Going to close this out. Let me know if issues persist and I can open it again.

**Comment by BMayneFactual** [comment]
I see this on v0.10.31. Will update.
