### ISSUE TITLE
Need high res images for retina, look like poo poo in retina

### ISSUE THREAD

**Issue by masterkrang** [lambtron/emojipacks#42]
![image](https://cloud.githubusercontent.com/assets/452219/17003848/b7482e2e-4e86-11e6-8453-22e10d97762a.png)

**Comment by Templarian** [comment]
If you use the ones from... [slack-emoji-pokemon](https://github.com/Templarian/slack-emoji-pokemon) they are 128x128 and should look nice. It only contains the Pokemon Go 152 unfortunately until they add more.

**Comment by zachfeldman** [comment]
@Templarian please feel free to submit a PR with these ones! Thanks :D

**Comment by Templarian** [comment]
@zachfeldman These were added months ago in a PR. Issue just didn't get closed. 😄

**Comment by zachfeldman** [comment]
Amazing! Thanks for the info @templarian
