### ISSUE TITLE
Issue using the pack

### ISSUE THREAD

**Issue by irongollem** [lambtron/emojipacks#44]
When going through the initial process I get to enter my company name and email, but after entering the email it does not proceed to the password step as if pending for some more information. Also tried enclosing the email in '' and "" but doesn't seem to work. Also tried your demo domain and email adress to see if it was something in the logging step. Using bash for windows to run the commands

**Comment by fahslaj** [comment]
I get this as well. Used the Git Bash for windows.

**Comment by hugovk** [comment]
I get the same with Git Bash, but it works with bog-standard cmd.exe (Windows 7).

**Comment by zachfeldman** [comment]
@irongollem @fahslaj @hugovk it has been a while since this has been filed and the repo has changed a lot since then. Closing, please reopen if this is still an issue or let us know here!
