### ISSUE TITLE
Does not work for Google Auth teams

### ISSUE THREAD

**Issue by rafaelmagu** [lambtron/emojipacks#5]
The app fails when trying to import packs into a Slack team that uses Google accounts for authentication.

```
(...)
Starting import
Uh oh! Error: Login error: could not get login form for https://myteam.slack.com
```

**Comment by lambtron** [comment]
Hmmm yes, i did _not_ consider this authentication method when building this. Sorry about that! Maybe I can add support for this at a later date.

**Comment by lambtron** [comment]
If we change the CLI to use Slack's auth system, then I think it'll solve this problem. I can take a look into it to see if it can work.

**Comment by danb235** [comment]
I ran into this issue as well.  +1

**Comment by haneetsingh** [comment]
Me too

**Comment by mtchllbrrn** [comment]
+1

**Comment by fkei** [comment]
+1

**Comment by boborchard** [comment]
+1 Any movement on adding Google Auth?

**Comment by kcharwood** [comment]
Seeing this too

**Comment by allixsenos** [comment]
:sob:

**Comment by zachfeldman** [comment]
Closing for now, but glad to accept a PR for this.
