### ISSUE TITLE
Create a new release for NPM?

### ISSUE THREAD

**Issue by kcharwood** [lambtron/emojipacks#50]
Thanks so much for the tool! I installed the version from NPM, but it failed to login. Looks like I needed the `no_sso` from #14, but I don't think that version has made it to NPM yet. I cloned the repo, and was able to use the updated codebase to upload a pack.

Would you be able to push a new version? I'd like to reference this tool in a blog post I'm writing soon about installing emoji packs into slack.

Thanks!

🍻

**Comment by lambtron** [comment]
Done! Thank you!
