### ISSUE TITLE
Improve the error messages

### ISSUE THREAD

**Issue by alecfwilson** [lambtron/emojipacks#6]
Somewhat minor, but when uploads aren't working, the terminal just hangs after entering the YAML file location. So far, I've always been able to solve it, but it's somewhat like searching for a needle in a haystack - so far, I've run into issues with:
- my YAML file format
- duplicate names between emojis in the YAML file and in my Slack account
- missing names for emojis in the YAML file
- incorrect file URLs for the emoji images
- had an upload hang after beginning to upload the first image (the hanging was a result of duplicate names), which I then killed and fixed the issue, but when I checked Slack, the emoji that began to upload had not been uploaded, yet I couldn't get the fixed YAML file to upload until I removed the image that began to upload in the last attempt 

It's been suggested that I run emojipacks with the -d flag, yet when I've tried this, nothing is output, as the command simply hangs and I have to kill it. It would be great if errors like this caused the command to fail with a message rather than simply hanging and relying on us to figure it out.

I'm not a formally trained programmer, but this might be an interesting problem for me, I've never written a CLI program though - if you know of any good resources for learning to write them, I'd potentially be interested in writing a fix for you - big fan of the tool!

**Comment by lambtron** [comment]
Hey, thanks for your interest in the project and especially for finding these edge cases :).

The `-d` flag actually just saves the HTML into one of the folders of the `emojipacks` directory itself. Probably not the most elegant solution on me; would've made more sense if i required you to pass an output directory for the HTML.

If you'd like to poke around, I'd recommend adding `console.log` and print random things out at random times to see how everything fits together :). I'm going to be out next week, but when I return, i'll be more than happy to investigate.

**Comment by zachfeldman** [comment]
Thanks @lambtron , looks like there are good instructions to investigate issues so closing this for now.
