### ISSUE TITLE
Problems in slackmojis.yaml

### ISSUE THREAD

**Issue by hugovk** [lambtron/emojipacks#65]
Found 27 errors in packs/slackmojis.yaml
Error: image can't be larger than 128px in width or height: (512, 512) http://emojis.slackmojis.com/emojis/images/1460283908/347/askfm.png
Error: image can't be larger than 128px in width or height: (180, 161) http://emojis.slackmojis.com/emojis/images/1458106637/314/flask.png
Error: image can't be larger than 128px in width or height: (263, 263) http://emojis.slackmojis.com/emojis/images/1450805181/256/gap.png
Error: image can't be larger than 128px in width or height: (225, 225) http://emojis.slackmojis.com/emojis/images/1460043575/341/git.png
Error: image can't be larger than 128px in width or height: (1000, 1000) http://emojis.slackmojis.com/emojis/images/1464897233/502/zeplin.png
Error: cannot open as image: http://emojis.slackmojis.com/emojis/images/1458326982/320/notbad.png
Error: image can't be larger than 128px in width or height: (192, 192) http://emojis.slackmojis.com/emojis/images/1450735566/237/slowpoke.jpg
Error: cannot open as image: http://emojis.slackmojis.com/emojis/images/1450319448/67/beachball.gif
Error: image can't be larger than 128px in width or height: (225, 224) http://emojis.slackmojis.com/emojis/images/1450799464/255/communist.png
Error: cannot open as image: http://emojis.slackmojis.com/emojis/images/1466642363/538/devil.gif
Error: cannot open as image: http://emojis.slackmojis.com/emojis/images/1467057004/597/doge.png
Error: image can't be larger than 128px in width or height: (256, 245) http://emojis.slackmojis.com/emojis/images/1456336445/300/excite_bike.png
Error: image can't be larger than 128px in width or height: (600, 450) http://emojis.slackmojis.com/emojis/images/1459899884/339/fail.jpg
Error: cannot open as image: http://emojis.slackmojis.com/emojis/images/1466718186/570/giggle.gif
Error: cannot open as image: http://emojis.slackmojis.com/emojis/images/1466718368/573/inlove.gif
Error: cannot open as image: http://emojis.slackmojis.com/emojis/images/1466718396/574/island.gif
Error: cannot open as image: http://emojis.slackmojis.com/emojis/images/1468001886/652/liono.png
Error: cannot open as image: http://emojis.slackmojis.com/emojis/images/1466718427/575/lips_sealed.gif
Error: image can't be larger than 128px in width or height: (235, 161) http://emojis.slackmojis.com/emojis/images/1461379139/374/nekoatsume.jpg
Error: cannot open as image: http://emojis.slackmojis.com/emojis/images/1466718469/576/plane.gif
Error: cannot open as image: http://emojis.slackmojis.com/emojis/images/1466642686/548/poke.gif
Error: cannot open as image: http://emojis.slackmojis.com/emojis/images/1466717309/560/poolparty.gif
Error: cannot open as image: http://emojis.slackmojis.com/emojis/images/1468525895/662/slowpoke.jpg
Error: cannot open as image: http://emojis.slackmojis.com/emojis/images/1470076018/692/tesla.jpeg
Error: cannot open as image: http://emojis.slackmojis.com/emojis/images/1450786255/254/tumbleweed.gif
Error: image can't be larger than 128px in width or height: (400, 400) http://emojis.slackmojis.com/emojis/images/1465426678/505/welcome.jpeg
Error: image can't be larger than 128px in width or height: (340, 291) http://emojis.slackmojis.com/emojis/images/1461187775/372/woot.jpg

cc @dleesalestreamsoft @lambtron

**Comment by hugovk** [comment]
Here's resized versions of:
* askfm.png
* communist.png
* excite_bike.png
* fail.jpg
* flask.png
* gap.png
* git.png
* nekoatsume.jpg
* slowpoke.jpg
* woot.jpg
* zeplin.png

[slackmojis-resized.zip](https://github.com/lambtron/emojipacks/files/752836/slackmojis-resized.zip)

**Comment by zachfeldman** [comment]
Merged!
