### ISSUE TITLE
Upload all files

### ISSUE THREAD

**Issue by lookfirst** [lambtron/emojipacks#7]
One at a time is a pain in the :hankey:

**Comment by lambtron** [comment]
Hmm yeah good idea. Still need to do some thinking as to what is the best way. Probably in the prompt, it'll just loop through asking for yaml files or something.

**Comment by lookfirst** [comment]
Just allow me to point at a folder full of yaml files... or just pull the folder/files directly from GH... or just include them in the npm package... doesn't need to be complicated...

**Comment by GeekOnCoffee** [comment]
Or you could combine the files...

**Comment by zachfeldman** [comment]
All great suggestions. Feel free to submit PRs! Closing for now.
