### ISSUE TITLE
UnhandledPromiseRejectionWaringin error

### ISSUE THREAD

**Issue by melinerunen** [lambtron/emojipacks#73]
After the unhandled exepcion the app doesn't properly exit to the terminal:

<img width="1064" alt="screen shot 2016-12-27 at 11 24 00" src="https://cloud.githubusercontent.com/assets/1240420/21501460/00bb9226-cc27-11e6-86de-07ba8d17db11.png">

**Comment by zachfeldman** [comment]
@melinerunen this can be solved with Ctrl + C. Feel free to submit a pull request if this solution doesn't work well for you!
