### ISSUE TITLE
Missing command parameteres

### ISSUE THREAD

**Issue by melinerunen** [lambtron/emojipacks#74]
It will be nice to add command parameters in order to add it to a silent script upload. Ie:

emojipacks -d \<slackdomain\> -u \<username\> -p \<password\> \<file.yaml\>
or emojipacks \<file.yaml\>

**Comment by zachfeldman** [comment]
@melinerunen pretty good idea! We are about to merge a PR with YAML configuration of these parameters....however if you submit a PR with this, I wouldn't be opposed to merging it. Closing for now though
