### ISSUE TITLE
Running "emojipacks" results in: /usr/bin/env: ‘node --harmony’: No such file or directory

### ISSUE THREAD

**Issue by asachs01** [lambtron/emojipacks#75]
To give a bit more detail, here is the system I'm currently running:

```
OS: Korora 25
Kernel: 4.8.15-300.fc25.x86_64
Node version: v6.9.1
NPM version: 3.10.8
```

After finding https://bbs.archlinux.org/viewtopic.php?id=168479, it seems that to resolve the error, changing the shebang to `#!/usr/bin/node` will allow the program to run without presenting the error.

**Comment by zachfeldman** [comment]
@asachs01 it sounds like you've figured this one out so I'm closing. Feel free to open if not!
