### ISSUE TITLE
"/usr/bin/env node --harmony: no such file or directory"

### ISSUE THREAD

**Issue by bchalls** [lambtron/emojipacks#94]
The env command on some *nix systems or git bash on Windows can only accept one argument, so you will receive this error if you try and run emojipacks: "/usr/bin/env node --harmony: no such file or directory"

A potential fix is to remove the --harmony option. This does not seem to cause any issues when running with the latest stable build of node.

**Comment by zachfeldman** [comment]
Thanks for bringing to our attention @bchalls . Mind submitting a PR to ameliorate?

**Comment by hugovk** [comment]
https://github.com/lambtron/emojipacks/pull/96 is merged, this can be closed. 👍
