### ISSUE TITLE
add mattermost support

### ISSUE THREAD

**Issue by jerome-vai** [lambtron/emojipacks#97]
add support of mattermost (open source clone of slack)

**Comment by zachfeldman** [comment]
@jeje-50 sure, would you like to submit a pull request to do so?

**Comment by jerome-vai** [comment]
@zachfeldman i'am a newbie on JS world 😄

**Comment by lisaah** [comment]
I've made this before for bulk emoji transfer on Mattermost, if it helps: https://github.com/lisamai/emojiporter

**Comment by zachfeldman** [comment]
V cool. Going to close this issue then...
