### ISSUE TITLE
error: unknown option `-s'

### ISSUE THREAD

**Issue by snipe** [lambtron/emojipacks#98]
Hi there!

I'm running into an issue when I try to run this script via batch or in the one-line version (not interactive mode). 

```
 snipe@deepthought ~/Sites/emojipacks$ sh ./batchUpload.sh
./packs/animals.yaml

  error: unknown option `-s'

./packs/businessfish.yaml

  error: unknown option `-s'

./packs/clippy.yaml

  error: unknown option `-s'
... etc... 
```
This seems to happen regardless of whether I pass the optional path:

```
snipe@deepthought ~/Sites/emojipacks$ sh ./batchUpload.sh packs
./packs/animals.yaml

  error: unknown option `-s'

./packs/businessfish.yaml

  error: unknown option `-s'

./packs/clippy.yaml

  error: unknown option `-s'
```

And also in the one-liner.

```
snipe@deepthought ~/Sites/emojipacks$ emojipacks -s MYSLACKNAME -e MYSLACKEMAIL -p MYSLACKPASSWORD -y ./packs/animals.yaml

  error: unknown option `-s'
```

Installed via npm.

I'm probably missing something really obvious. ☹️  Any ideas?

Thanks!

**Comment by zachfeldman** [comment]
Paging @bchalls ! He authored the PR for this. Any ideas halls?

**Comment by bchalls** [comment]
The npm version doesn't seem to be in sync with the repo. If you build from source that shell script should work.

**Comment by zachfeldman** [comment]
@bchalls do we need to do a new build/reissue or is this more of a @snipe specific issue? Thanks for the quick response!

**Comment by bchalls** [comment]
Since the batchUploads script isn't included with the npm version there is no immediate need to submit a new build. However the current npm version does not support command line arguments. (Which is why the script isn't working)

**Comment by zachfeldman** [comment]
Cool @bchalls , what version should we bump to then?

**Comment by bchalls** [comment]
If you're doing release.feature.bugfix versioning: 0.2.0

**Comment by zachfeldman** [comment]
@bchalls just released a new version on NPM, agreed that release.feature.bugfix is a good way to go about it (basically semver, right)?

@snipe does this version fix things for you? If not we may need a PR. If yes I'll close this out.

**Comment by snipe** [comment]
I can confirm that `npm update -g emojipacks` fixed the issue. Thanks so much for the lightning fast response! As a thank you, I just submitted a PR for an emojipack :)

![high-five](https://cloud.githubusercontent.com/assets/197404/24536768/9f0d198c-1591-11e7-9e13-46e10a45e264.gif)

**Comment by zachfeldman** [comment]
Moar emojipacks are the best reward!
